#!/usr/bin/env bash
# Script to display info about our sub domains
domain_info () {
	SUB_DOMAIN="$2"
	RECORD_TYPE=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $4}')
	DESTINATION=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $5}')
	echo "The subdomain ${SUB_DOMAIN} is a ${RECORD_TYPE} record and points to ${DESTINATION}"
}
if [ "$#" -eq 1 ]
then
    domain_info "www.${1}" "www"
    domain_info "lb-01.${1}" "lb-01"
    domain_info "web-01.${1}" "web-01"
    domain_info "web-02.${1}" "web-02"
else
    domain_info "$2.$1" "$2"
fi
