#!/usr/bin/env bash
# Configures and ubuntu server with redirection
sed_string="server_name _;\nrewrite ^/redirect_me$ https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;\n"
sed -i "s,server_name _;,$sed_string," /etc/nginx/sites-available/default
systemctl restart nginx
