#!/usr/bin/env bash
# Configures and ubuntu server with redirection
apt-get -y update
apt-get -y install nginx
touch /var/www/html/index.html
echo 'Holberton School' > /var/www/html/index.html
sed_string="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "s,server_name _;,$sed_string," /etc/nginx/sites-available/default
service nginx restart
