#!/usr/bin/env bash
# Configure nginx server
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
cat > '/etc/nginx/sites-available/default' <<EOF
server {
    listen 80 default_server;
    listen [::]:80 ipv6only=on default_server;

    add_header X-Served-By \$hostname;

    root /var/www/html;
    index index.html;

    error_page 404 /custom_404.html;
    location /custom_404.html {
    	     root /usr/share/nginx/html;
             internal;
    }
    location /redirect_me {
    	     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
service nginx restart
