#!/usr/bin/env bash
# A script to run whoami
#localedef -i en_US -f UTF-8 en_US.UTF-8
#if id -u "$1" > /dev/null 2>&1; 
#then
sudo -u "$1" whoami
#else 
#    adduser --quiet --disabled-password --gecos "" "$1"
#    sudo -u "$1" whoami
#fi
