#!/usr/bin/env bash
# Fixes a container to run as not root, but new user nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's| 80 | 8080 |' /etc/nginx/sites-available/default
sed -i 's|:80 |:8080 |' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
